# Generated by Django 4.0.6 on 2023-05-27 06:31

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_solicitudservicio_horavisita'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudservicio',
            name='precio',
            field=models.IntegerField(default=25000),
        ),
        migrations.AlterField(
            model_name='solicitudservicio',
            name='descsol',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='solicitudservicio',
            name='horavisita',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='hora de visita'),
        ),
        migrations.AlterField(
            model_name='solicitudservicio',
            name='nrofac',
            field=models.ForeignKey(db_column='nrofac', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.factura'),
        ),
        migrations.AlterField(
            model_name='solicitudservicio',
            name='ruttec',
            field=models.ForeignKey(db_column='ruttec', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.perfilusuario'),
        ),
        migrations.AlterField(
            model_name='solicitudservicio',
            name='tiposol',
            field=models.CharField(choices=[('1', 'Instalación'), ('2', 'Mantención'), ('3', 'Reparación')], default='2', max_length=1, verbose_name='Tipo de Solicitud'),
        ),
    ]
